### ISSUE TITLE
Warning: Undefined variable $layer in C:\Users\USERNAME\Desktop\phpmp3.php on line 260 PHP Warning:  Undefined variable $layer in C:\Users\USERNAME\Desktop\phpmp3.php on line 263

### ISSUE THREAD

**Issue by nabilkrs** [thegallagher/PHP-MP3#4]
Here is my php code

require_once 'phpmp3.php';
$path = 'song.mp3';
$mp3 = new PHPMP3($path);
$mp3_1 = $mp3->extract(10,30);
$mp3_1->save('newpath.mp3');

please help

**Comment by basemkhirat** [comment]
Having same issue.
